# Remove obsolete version tag
# version: '3.8'

services:
  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5001:5001"
    volumes:
      - ./mlruns:/mlflow_runs
      - ./mlartifacts:/mlflow_artifacts
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5001"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile  # Your main backend Dockerfile
    ports:
      - "${API_PORT:-8000}:8000"
    depends_on:
      mlflow-server:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL_PYMSSQL}
      - DATABASE_URL_PYMSSQL=${DATABASE_URL_PYMSSQL}
      - MLFLOW_TRACKING_URI=http://mlflow-server:5001
      - DB_PREDICTION_LOG_TABLE=${DB_PREDICTION_LOG_TABLE:-prediction_logs}
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app:/app/src
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    command: ["uvicorn", "employee_attrition_mlops.api:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT:-8501}:8501"
    depends_on:
      api:
        condition: service_started
    environment:
      - API_URL=http://api:8000
    volumes:
      - ./src/frontend:/app/src/frontend
      - ./.env:/app/.env
    command: ["streamlit", "run", "src/frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
