channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=23.3.2
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.1.1
  - imbalanced-learn==0.12.4
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==7.0.0
  - python-dotenv==1.1.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - sqlalchemy==2.0.40
name: mlflow-env
