name: Model Promotion

on:
  pull_request_review:
    types: [submitted]

jobs:
  promote_model:
    if: github.event.review.state == 'approved' && contains(github.event.pull_request.labels.*.name, 'model-promotion')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry config virtualenvs.create false
    
    - name: Install dependencies
      run: |
        poetry install
    
    - name: Start MLflow server
      run: |
        poetry run mlflow server --host 127.0.0.1 --port 5001 &
        sleep 5  # Wait for server to start
    
    - name: Promote model
      id: promote
      run: |
        # Extract run_id from PR description if available
        RUN_ID=$(echo "${{ github.event.pull_request.body }}" | grep -oP 'MLflow Run ID: \K[a-f0-9]+' || echo "")
        
        if [ -n "$RUN_ID" ]; then
          poetry run python scripts/promote_model.py --run-id $RUN_ID
        else
          # If no run_id found, promote latest staging model
          poetry run python scripts/promote_model.py
        fi
      env:
        MLFLOW_TRACKING_URI: http://127.0.0.1:5001
    
    - name: Create comment
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const message = context.job.status === 'success'
            ? '✅ Model successfully promoted to production!'
            : '❌ Model promotion failed. Please check the workflow logs.';
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: message
          });

    - name: Handle failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '⚠️ Model Promotion Failed',
            body: 'The model promotion workflow failed. Please check the workflow logs and retry if necessary.',
            labels: ['model-promotion-failed']
          });